### ISSUE TITLE
getUserAllRatings Server Error 

### ISSUE THREAD

**Issue by venca163** [Mikulas/csfd-api#11]
Hi,

I have noticed, that if you try to get all ratings of user (http://csfdapi.cz/user/*/ratings) you can get Server Error. 

I have found out 2 cases:

1) when user have only 1 page of ratings
example: http://csfdapi.cz/user/366479/ratings?type=html

2) when user have no ratings
example: http://csfdapi.cz/user/110589/ratings?type=html

**Comment by Mikulas** [comment]
:+1:  great, thanks, should be fixed now

**Comment by venca163** [comment]
thx, good job =)
