### ISSUE TITLE
FR: Missing rating in author data

### ISSUE THREAD

**Issue by hawwwran** [Mikulas/csfd-api#16]
Hi,
I'm missing rating group (0-3) in author data. It's the colored squares.
Thank you

**Comment by Mikulas** [comment]
Hi,
what colored squares do you mean exactly? These: ?
![screenshot 2014-05-05 18 33 02](https://cloud.githubusercontent.com/assets/192200/2880218/02471b00-d473-11e3-928c-0841b326f3e7.png)

**Comment by hawwwran** [comment]
No, not those. These (in attachment) with class="film cX" where X is number
0-3

2014-05-05 18:34 GMT+02:00 Mikuláš Dítě notifications@github.com:

**Comment by Mikulas** [comment]
Oh I get it. That is mostly by design. The api expects you would load those movies anyway to get the full rating scale. Not awesome at all, but I don't want to hammer csfd servers that hard to get the full rating.

Sorry, this is a wont-fix.

**Comment by hawwwran** [comment]
O to právě jde, aby se nemuselo načítat všech x filmů, abych získal přehled
o ratingu. Tohle jde zjistit z té class už při načítání všeobecných
informací = není potřeba žádný další request na csdf.
Dne 5. 5. 2014 18:44 "Mikuláš Dítě" notifications@github.com napsal(a):

**Comment by Mikulas** [comment]
je mi to jasný, ale je to taková polovičatá informace co by se tam měla zobrazovat. Chápu, proč by se to mohlo hodit. Stejně tak search vrací jenom jméno a id atp. Nechci jenom kopírovat 1:1 stránky z csfd, chci aby to api dávalo smysl samo o sobě :)

**Comment by hawwwran** [comment]
Pak by to mohlo být přepočítáno v procentech, ale ztratila by se 0
(nehodnoceno). Je to prostě informace která se vážně hodí. Nevidím bez ní
kvalitu filmů u herce, aniž bych těch někdy desítky filmů načetl kompletně.
To by kvůli tak drobné informaci trvalo načtení herce hroznou dobu a brzo
by to csfd zatrhlo.
Viděl bych to jako rating_group=0-3 a u detailu (movie) by to šlo pro
úplnost dopsat také, dopočítáním z rating, aby to dávalo smysl a bylo
konzistentní.
Dne 5. 5. 2014 18:57 "Mikuláš Dítě" notifications@github.com napsal(a):

**Comment by Mikulas** [comment]
Je to větší změna, muselo by se to projevit na i na vyhledávání filmů a muselo by se to vracet i při samotném requestu na film. Jestli uděláš pull request tak ho přidám :) v dohledný době se nedostanu k tomu abych to implementoval.
On 5 May 2014 at 19:03:47, hawwwran (notifications@github.com) wrote:

Pak by to mohlo být přepočítáno v procentech, ale ztratila by se 0
(nehodnoceno). Je to prostě informace která se vážně hodí. Nevidím bez ní
kvalitu filmů u herce, aniž bych těch někdy desítky filmů načetl kompletně.
To by kvůli tak drobné informaci trvalo načtení herce hroznou dobu a brzo
by to csfd zatrhlo.
Viděl bych to jako rating_group=0-3 a u detailu (movie) by to šlo pro
úplnost dopsat také, dopočítáním z rating, aby to dávalo smysl a bylo
konzistentní.
Dne 5. 5. 2014 18:57 "Mikuláš Dítě" notifications@github.com napsal(a):

**Comment by hawwwran** [comment]
Neumim si proste predstavit, jak pomoci csfdapi udelat interface, ktery
hned v seznamu filmu informuje uzivatele o hodnoceni (tonje hodne
dulezite). Pritom nactenim teto informace z detailu stejne povede k
jednoduchemu zobrazeni, protoze ukazovat cele cislo je neprehledne. To jak
to vyresilo csfd je proste idealni reseni tohoto problemu.
Dne 5. 5. 2014 19:03 "Hawwwran" info@hawwwran.com napsal(a):

**Comment by hawwwran** [comment]
Ok, mrknu na pull request (nevim co to je, sam pouzivam mercurial). Dekuju
Dne 5. 5. 2014 19:09 "Hawwwran" info@hawwwran.com napsal(a):
