### ISSUE TITLE
names vs name

### ISSUE THREAD

**Issue by michalfuka** [Mikulas/csfd-api#18]
chyba klíče u struktury Movie. Pokud parsuji json data z url /movie/[i:id], tak je klíč pojmenován names, pokud ale parsuji json data z url /author/[i:id] a snažím se získat výčet filmů (např. author-filmography-director), pak je klíč pojmenován name. Přitom z api by se mělo jednat o stejnou strukturu Movie, tudíž by klíč měl být v obou případech names.

**Comment by Mikulas** [comment]
Díky, opravil jsem to. Kvůli zpětné kompatibilitě jsem původní klíč zachoval.

**Comment by michalfuka** [comment]
Děkuji za komunikaci a především za api. Ještě jsem si všiml jedné 
drobnosti. Pole names u struktury Movie v některých případech obsahuje html 
entity. V api o tom není zmínka ;-). Jedná se např o film s id=123.

S pozdravem

Michal Fuka

---------- Původní zpráva ----------
Od: Mikuláš Dítě notifications@github.com
Komu: Mikulas/csfd-api csfd-api@noreply.github.com
Datum: 2. 6. 2014 16:25:49
Předmět: Re: [csfd-api] names vs name (#18)

"

Díky, opravil jsem to. Kvůli zpětné kompatibilitě jsem původní klíč 
zachoval.

—
Reply to this email directly or view it on GitHub
(https://github.com/Mikulas/csfd-api/issues/18#issuecomment-44843104). 

"
