### ISSUE TITLE
Nemožný přístup přes XMLHttpRequest

### ISSUE THREAD

**Issue by voslartomas** [Mikulas/csfd-api#4]
Zdravím, bylo by možné k API dopsat hlavičku: Access-Control-Allow-Credentials: true. Nyní není možné se připojit přes ajaxový request, snažím se využít této API v jedné aplikaci a tohle je trošku problém.

**Comment by Mikulas** [comment]
to je fakt, přidal jsem

```
Access-Control-Allow-Credentials:true
Access-Control-Allow-Origin:*
```

takže by to už mělo být v pohodě.

**Comment by voslartomas** [comment]
Ano funguje skvěle, díky.
