### ISSUE TITLE
Nedostupnost API

### ISSUE THREAD

**Issue by voslartomas** [Mikulas/csfd-api#5]
Ahoj,

můžu se zeptat jestli bude API dostupná do tohoto čtvrtka?

**Comment by Mikulas** [comment]
Hádám, že ne. :-1:  :/ https://twitter.com/MartinMajor/status/331180791063261185
je to škoda, ale pořád můžeš použít ten parser lokálně. Není to ideální, ale nic lepšího asi není.

**Comment by voslartomas** [comment]
No teď to funguje zrovna, tak snad bude i ve čtvrtek potřeboval bych odevzdat projekt alespoň:)

**Comment by Mikulas** [comment]
Aha, paráda, já jsem ten block čekal permanentnější. Nasadil jsem tam hnedka docela ostré limity, abych dalším blockům předešel -- kdyby s tím byl problém (tzn. hlásilo ti to `Too many API calls` moc často), tak dej vědět.
